### ISSUE TITLE
Plot contamination rates as a function of time

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_qc#144]

**Comment by jkgoodrich** [comment]
This plot and code for it can be found in this HTML: gs://gnomad-julia/gnomad_v4/sample_qc_improvement_plots.html

There was somewhat limited data on this in v2. I used the gvcf_date for time. For v3.1, Sam grabbed the PDO list for me with dates. I mapped that onto the v3.1 meta HT. For samples with multiple PDO's listed I chose the most recent PDO. 

Currently the plots don't have labels, but the x-axis is date and the y-axis is freemix.

**v2:**
![v2_contamination_time.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/09060603-d946-4afc-99f0-4ad487dad49e)


**v3:**
![v3_contamination_time.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/62375576-3e25-4190-9d69-1aafc53cb709)

There are some odd patterns in the v3 plot so I need to look into and make sure I did things correctly, will update after looking into it more.

**Comment by jkgoodrich** [comment]
I figured out the problem with the v3 plot. I forgot to remove the tumor samples and I wasn't correctly choosing only the most recent PDO for a sample.

v2:
![bokeh_plot - 2021-09-30T171607.037.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/4a710b5b-d44c-4b26-a80f-208d4f7946d6)

v3:
![bokeh_plot - 2021-09-30T171609.820.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/df709f36-cf60-457a-b982-5f2d43868bdf)

**Comment by gtiao** [comment]
Why are the genomes so much more highly contaminated (whole percentage points) compared to the exomes? Could you plot these with a different color for the samples we ended up releasing versus filtering, just as a sanity check?

**Comment by gtiao** [comment]
I see in the HTMLs that a lot of the samples with sex aneuploidy have high contamination, so it seems likely that like we're capturing both true aneuploidy and contamination.

**Comment by jkgoodrich** [comment]
Additional analyses that came up at the MPG/DSP meeting:
- Percent of samples that fail over time because of contamination At both 5% and 2.5%
- Percent of samples that fail over time because for any reason (high quality).
- Look at the projects for the high samples

**Comment by jkgoodrich** [comment]
Percent of samples that fail over time (grouped by month) because of contamination at 5%, 2.5% and 1%. Note difference in range for the 1% plots. 
![Screen Shot 2021-11-10 at 2.50.43 PM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/b14fa612-435d-45a1-a2f2-74feff726f80)

Here I put the 1% on the same range, so values are cut off, but it’s easier to compare the majority of the months
![Screen Shot 2021-11-10 at 2.59.44 PM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/40812109-8d4f-4ad8-b6e4-aa2b4c2004fc)

Percent of samples that fail over time because for any reason (high quality).
![Screen Shot 2021-11-10 at 2.11.53 PM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/ce37246b-65b0-4ba9-b96a-4fc8729fb8a1)


It’s hard to say with the exomes if newer samples had lower levels of contamination given that the last point there is in 2016. For the genomes there is a peak over 2016 for the 2.5% and 1% cutoffs, but other than that the percent filtered is lower after that. There doesn't seem to be a huge difference between the 5% and the 2.5%.

**Comment by jkgoodrich** [comment]
We have decided to stay conservative at 5%. Note this will still be evaluated specifically for v4. Final discussion here: https://atgu.slack.com/archives/CRA2TKTV0/p1635353104004800
