### ISSUE TITLE
Plot distribution of contamination estimates stratified by sex aneuploidy status

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_qc#146]

**Comment by jkgoodrich** [comment]
This plot and code for it can be found in this HTML: gs://gnomad-julia/gnomad_v4/sample_qc_improvement_plots.html

There is no freemix info for v2 genomes, so I have v2 exomes and v3. 

**v2 exomes:**
![Screen Shot 2021-09-30 at 4.22.27 PM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/70bc7507-2fdf-4d88-894b-a969a77695ec)

v3 (It says exomes, but this is obviously genomes, I just need to change the title later):
![Screen Shot 2021-09-30 at 4.22.39 PM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/b05f8dae-6d50-4c88-8624-fbc8e4b782b8)

**Comment by jkgoodrich** [comment]
Additional analyses for this ticket that came up at the MPG/DSP meeting:
- Add ambiguous sex to plot
- Count of samples that would have been kept if not for sex check 
- Count of samples that are actually aneuploidy/ambiguous 
- Check to see if these are clustered in specific ancestries or projects

**Comment by jkgoodrich** [comment]
**Adding ambiguous sex to the plots:**
![Screen Shot 2021-11-10 at 2.14.07 PM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/1fcf67db-3556-44f3-bba8-e05d82ec3006)

There is now a significantly more pronounced hump at 10 percent contamination in the v2 exomes specifically when adding the ambiguous sex samples to the plot.


![Screen Shot 2021-11-10 at 2.14.41 PM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/6e316dce-50e2-4a81-bb71-feec1a472d27)

I can't check ancestry very well because we exclude these samples before ancestry and many don't have "known labels" (ignore project_id header, quick copy paste)
v2:
![Screen Shot 2021-11-10 at 3.23.56 PM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/b6f5d650-2f11-4060-bcbf-d120804c6b7a)
 
v3:
![Screen Shot 2021-11-10 at 3.23.52 PM.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/0cad6fc2-4cb0-4986-a157-ec6ee5235953)

**Counts and proportions by project_id:**
[https://app.zenhub.com/files/153521178/e9617513-c812-47f1-9105-4af2649e0e42/download](https://app.zenhub.com/files/153521178/e9617513-c812-47f1-9105-4af2649e0e42/download)

There are certainly some projects that have very high proportions (and reasonable counts) in v2.  Here are the ones above 5%:
C978
C977
C1760
C996
C470

For v3, all those above 5% had very low sample counts (most 1). Here are the ones with the top counts with a proportion over 1%:
![image.png](https://images.zenhubusercontent.com/5f4d3fb5900ef2def7626452/9d35f679-8347-47ec-b5a7-d03b1b094583)

**Comment by jkgoodrich** [comment]
Decided at gnomAD project meeting that this would be substantive work with minimal pay off. We can revisit at a later time, but this will not be part of gnomAD v4
