### ISSUE TITLE
Duplicate variants in the gnomad_exome_v2.1.1_hg38 dataset

### ISSUE THREAD

**Issue by amieeyun** [broadinstitute/gnomad_qc#55]
Hi，
There exist more than 2000 duplicate variants in the gnomad_exome_v2.1.1_hg38 dataset but the allele frequency is different, like chr1-12827274-12827274-C-T。

**Comment by gtiao** [comment]
I think this is a liftover issue. We should add a note about this in the
FAQ. Can someone remind me if the VCF contains the original coordinates, so
that users can trace the variant to its hg37 coordinates?


Grace Tiao
Associate Director, Computational Genomics
Translational Genomics Group | Medical and Population Genetics

The Broad Institute
105 Broadway
Cambridge, MA 02142
Tel: (617) 714-8523

**Comment by ch-kr** [comment]
Thanks for leaving the variant example. I checked the liftover Hail Table for this variant and confirmed this is a liftover issue. Two separate hg19 variants (1-13646320-G-A, 1-12887133-C-T) lifted over to the same location in hg38. To check if a duplicate variant is caused by multiple variants lifting to the same position, I recommend checking the following fields:
```
##INFO=<ID=OriginalContig,Number=1,Type=String,Description="The name of the source contig/chromosome prior to liftover.">
##INFO=<ID=OriginalStart,Number=1,Type=String,Description="The position of the variant on the source contig prior to liftover.">
##INFO=<ID=ReverseComplementedAlleles,Number=0,Type=Flag,Description="The REF and the ALT alleles have been reverse complemented in liftover since the mapping from the previous reference to the current one was on the negative strand.">
```

This liftover issue (seemingly duplicate variants) is documented in the FAQ under this question: https://gnomad.broadinstitute.org/faq#when-are-exomes-going-to-be-available-on-grch38
